name: 🐞 Bug Report
description: Create a report to help us improve docmd
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: docmd version
      description: What version of docmd are you using? (e.g. 0.2.6)
      placeholder: 0.2.6
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: v20.x
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS/Browser
      options:
        - macOS / Safari
        - Windows / Edge
        - Linux / Chrome
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the behavior.
      placeholder: |
        1. Run 'docmd init'
        2. Add configuration...
        3. Run 'docmd build'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.