// Source file from the docmd project — https://github.com/docmd-io/docmd

const path = require('path');
const fs = require('./fs-utils');
const esbuild = require('esbuild');

const DOCMD_HEADER = `/*! Source file from the docmd project — https://github.com/docmd-io/docmd */\n\n`;

/**
 * Recursively copies assets from src to dest.
 * Minifies CSS/JS files and adds docmd header.
 * 
 * @param {string} srcDir - Source directory
 * @param {string} destDir - Destination directory
 * @param {object} options - { minify: boolean }
 */
async function processAssets(srcDir, destDir, options = { minify: true }) {
  // Ensure source exists
  if (!await fs.exists(srcDir)) return;

  // Ensure dest exists
  await fs.ensureDir(destDir);

  const entries = await fs.readdir(srcDir, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);

    if (entry.isDirectory()) {
      await processAssets(srcPath, destPath, options);
    } else {
      const ext = path.extname(entry.name).toLowerCase();
      
      // Handle CSS & JS: Minify + docmd Header
      if (ext === '.css' || ext === '.js') {
        try {
          const content = await fs.readFile(srcPath, 'utf8');
          
          if (options.minify) {
            // Minify using esbuild
            const result = await esbuild.transform(content, {
              loader: ext.slice(1), // 'css' or 'js'
              minify: true,
              banner: ext === '.css' || ext === '.js' ? DOCMD_HEADER : ''
            });
            await fs.writeFile(destPath, result.code);
          } else {
            // Just add banner if not minifying (Dev mode)
            const contentWithBanner = `${DOCMD_HEADER}\n${content}`;
            await fs.writeFile(destPath, contentWithBanner);
          }
        } catch (e) {
          console.warn(`⚠️ Processing failed for ${entry.name}, copying original.`);
          await fs.copy(srcPath, destPath);
        }
      } 
      // Handle HTML Files (if any in assets): HTML Comment Header
      else if (ext === '.html') {
        const content = await fs.readFile(srcPath, 'utf8');
        const htmlBanner = `<!-- Generated by docmd - https://docmd.io -->\n\n`;
        await fs.writeFile(destPath, htmlBanner + content);
      }
      // Everything else (Images, Fonts): Direct Copy
      else {
        await fs.copy(srcPath, destPath);
      }
    }
  }
}

module.exports = { processAssets, DOCMD_HEADER };