#!/usr/bin/env node
/**
 * Manual entry point for `pnpm dev`, `pnpm build`, and `pnpm live`.
 * Validates that tarballs exist (error if not, prompt to run pnpm prep),
 * runs `npm install` lazily on first use, then runs the requested docmd
 * command in-place. Errors with a clear message instead of failing with
 * a cryptic "module not found" on a fresh clone that hasn't run prep yet.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tarsDir = path.join(__dirname, 'local-tars');
const nodeModules = path.join(__dirname, 'node_modules');

const command = process.argv[2];
if (!['dev', 'build', 'live'].includes(command)) {
  console.error(`Usage: node _playground/dev.js <dev|build|live>`);
  process.exit(1);
}

function fail(msg) {
  console.error(`\n  \x1b[31m✗\x1b[0m ${msg}\n`);
  process.exit(1);
}

// Tarballs must be present. Generated by pnpm prep, never on demand here.
if (!existsSync(tarsDir)) {
  fail('_playground/local-tars/ not found. Run `pnpm prep` first to build the monorepo and generate tarballs.');
}
const tars = existsSync(tarsDir) ? readdirSync(tarsDir).filter((f) => f.endsWith('.tgz')) : [];
if (tars.length === 0) {
  fail('_playground/local-tars/ is empty. Run `pnpm prep` first to generate tarballs.');
}

// node_modules — install lazily on first dev/build/live run so `pnpm prep`
// does not pollute _playground with a full install (prep only writes tars).
const env = { ...process.env };
delete env.npm_config_npm_globalconfig;
delete env.npm_config_verify_deps_before_run;
delete env.npm_config__jsr_registry;

if (!existsSync(nodeModules)) {
  console.log(`\n  \x1b[36m→\x1b[0m installing _playground dependencies (one-time)…\n`);
  // --include=optional picks up engine-rust / engine-rust-binaries so
  // docmd doesn't lock trying to load a missing native module. Pair with
  // --foreground-scripts to surface postinstall output (engine-rust's
  // postinstall downloads the .node binary from a CDN).
  let r = spawnSync('pnpm', ['install'], {
    cwd: __dirname,
    stdio: 'inherit',
    env,
  });
  if (r.status !== 0) {
    r = spawnSync('npm', ['install', '--no-audit', '--no-fund', '--legacy-peer-deps', '--include=optional', '--foreground-scripts'], {
      cwd: __dirname,
      stdio: 'inherit',
      env,
    });
  }
  if (r.status !== 0) fail(`install failed (exit ${r.status})`);
}

const binName = command === 'live' ? 'docmd-live' : 'docmd';
const localBin = path.join(__dirname, 'node_modules', '.bin', binName);
const executable = existsSync(localBin) ? localBin : binName;
const r = spawnSync(executable, command === 'live' ? [] : [command], { cwd: __dirname, stdio: 'inherit', env });
process.exit(r.status ?? 0);